In [1]:
import pandas as pd
import numpy as np


In [2]:
from sklearn.model_selection import train_test_split

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

In [4]:
spam = pd.read_csv("spam.csv", encoding='iso-8859-1')

FileNotFoundError: [Errno 2] No such file or directory: 'spam.csv'

In [8]:
spam

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [11]:
spam.groupby('v1').describe()

v2                                                                 \
     count unique                                                top freq   
v1                                                                          
ham   4825   4516                             Sorry, I'll call later   30   
spam   747    653  Please call our customer service representativ...    4   

     Unnamed: 2                                                            \
          count unique                                                top   
v1                                                                          
ham          45     39   bt not his girlfrnd... G o o d n i g h t . . .@"   
spam          5      4                                        PO Box 5249   

          Unnamed: 3                                    Unnamed: 4         \
     freq      count unique                    top freq      count unique   
v1                                                                          
ham     3         10      9                     GE    2          6      5   
spam    2          2      1   MK17 92H. 450Ppw 16"    2          0      0   

                    
          top freq  
v1                  
ham   GNT:-)"    2  
spam      NaN  NaN

In [13]:
spam["spam"]=spam['v1'].apply(lambda x: 1 if x== 'spam' else 0)

In [14]:
spam

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  spam  
0           NaN        NaN     0  
1           NaN        NaN     0  
2           NaN        NaN     1  
3           NaN        NaN     0  
4           NaN        NaN     0  
...         ...        ...   ...  
5567        NaN        NaN     1  
5568        NaN        NaN     0  
5569        NaN        NaN     0  
5570        NaN        NaN     0  
5571        NaN        NaN     0  

[5572 rows x 6 columns]

In [16]:
x_train , x_test, y_train, y_test = train_test_split(spam.v2, spam.spam)

In [17]:
x_train

3144           I.ll get there tomorrow and send it to you
4889    Sounds like there could be a lot of time spent...
613     THANX4 TODAY CER IT WAS NICE 2 CATCH UP BUT WE...
3983    Hey, I missed you tm of last night as my phone...
4188    Well the general price is  &lt;#&gt; /oz, let ...
                              ...                        
2252                 Den wat will e schedule b lk on sun?
1297               K so am I, how much for an 8th? Fifty?
1781                               ;-( oh well, c u later
1315    Whenevr ur sad, Whenevr ur gray, Remembr im he...
3921    Oh really? perform, write a paper, go to a mov...
Name: v2, Length: 4179, dtype: object

In [18]:
x_test

2191    Thankyou so much for the call. I appreciate yo...
3808              At the funeral home with Audrey and dad
1638                Great comedy..cant stop laughing da:)
4645    We tried to contact you re your reply to our o...
5283                      Yeah, probably here for a while
                              ...                        
4950    hi baby im sat on the bloody bus at the mo and...
4193          Can not use foreign stamps in this country.
988     Yun ah.the ubi one say if Ì_ wan call by tomor...
4772       Ok then u tell me wat time u coming later lor.
2121    In xam hall boy asked girl Tell me the startin...
Name: v2, Length: 1393, dtype: object

In [19]:
x_train.describe()

count                       4179
unique                      3936
top       Sorry, I'll call later
freq                          23
Name: v2, dtype: object

In [20]:
cv = CountVectorizer()
x_train_count = cv.fit_transform(x_train.values)

In [32]:
x_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [25]:
model= MultinomialNB()
model.fit(x_train_count,y_train)

MultinomialNB()

In [26]:
email_ham = ["hey wanna meet up for the game ?"]
email_ham_count= cv.transform(email_ham)
model.predict(email_ham_count)

array([0], dtype=int64)

In [28]:
email_spam = ["reward money click "]
email_spam_count= cv.transform(email_spam)
model.predict(email_spam_count)

array([1], dtype=int64)

In [29]:
x_test_count = cv.transform(x_test)
model.score(x_test_count, y_test)

0.9877961234745154

In [30]:
email_ham = ["baseball tickets later  "]
email_ham_count= cv.transform(email_ham)
model.predict(email_ham_count)

array([0], dtype=int64)

In [34]:
email_spam = ["successfully won 500000rs "]
email_spam_count= cv.transform(email_spam)
model.predict(email_spam_count)

array([1], dtype=int64)